from enum import Enum

class Power(Enum):
    """Enum des différents pouvoirs"""
    NO_FIRE = "no_fire" # ne peux pas recevoir de licenciement
    NO_DIVORCE = "no_divorce" # ne peux pas recevoir de divorce
    NO_TAX = "no_tax" # ne peux pas recevoir de taxe
    NO_MALADIE = "no_maladie" # ne peux pas recevoir de maladie
    NO_ACCIDENT = "no_accident" # ne peux pas recevoir d'accident
    NO_GOUROU = "no_gourou" # ne peux pas avoir de gourou dans la partie
    NO_ATTENTAT = "no_attentat" # ne peux pas y avoir un attentat dans la partie
    NO_BANDIT = "no_bandit" # ne peux pas avoir de bandit dans la partie
    NO_REDOUBLEMENT = "no_redoublement" # ne peux pas recevoir de redoublement
    NO_BURNOUT  = "no_burnout" # ne peux pas recevoir de carte burnout
    CAN_BE_JAILED = "can_be_jailed" # peut se prendre la carte prison
    FIRST_HOUSE_FREE = "first_house_free" # la première maison posée est gratuite
    HAS_BEEN_BANDIT = "has_been_bandit" # ce joueur a été bandit dans la partie
    CAN_BE_PRICED = "can_be_priced" # peut recevoir un grand prix d'excellence
    INFINITE_STUDY = "infinite_study" # peut étudier a l'infini
    TRAVEL_FREE = "travel_free" # les voyages sont gratuits
    INFINITE_FLIRT = "infinite_flirt" # peut flirter a l'infini
    GYNOCRATIE = "gynocratie" # les smiles des enfants garçons sont divisés par 2
    PHALOCRATIE = "phalocratie" # les smiles des enfants filles sont divisés par 2
    CHILDREN_PROTECTED = "children_protected" # tous les enfants du joueur sont protégés de tous les malus
    EGALITE_SALAIRE = "egalite_salaire" # permet de poser des salaires par rapport au métier le mieux payé
    GIRL_POWER = "girl_power" # permet de rejouer des cartes spéciales déja jouée lorsqu'on pose une fille
    JOB_MAX_STUDY_5 = "job_max_study_5" # le joueur peut avoir un job avec un niveau d'étude maximum de 5
    JOB_MAX_STUDY_4 = "job_max_study_4" # le joueur peut avoir un job avec un niveau d'étude maximum de 4
    INSTANT_QUIT_JOB = "instant_quit_job" # le joueur peut quitter n'importe quel métier sans avoir a passer son tour
    INSTANT_QUIT_WEDDING = "instant_quit_wedding" # le joueur peut quitter un marriage sans avoir a passer son tour
    CAN_PLAY_CHILD = "can_play_child" # permet au joueur de poser des enfants sans autre condition
    DOUBLE_STUDY = "double_study" # double les etudes
    RISTOURNELLE = "ristournelle" # réduit le prix des acquisition de 1
    CANT_PLACE_CARD = "cant_place_card" # ne peut plus jouer de carte
    TRAVEL_DOUBLE = "travel_double" # double les smiles des voyages
    BIS_REPETITAS = "bis_repetitas" # double la durée des effets des maladies, burnout, accident
    CAN_BE_TAXED = "can_be_taxed" # peut recevoir l'impot sur le revenue sans condition
    CAN_BE_BURN_OUT = "can_be_burn_out" # peut recevoir un burnout sans condition 
    MANO_NEGRA = "mano_negra" # déduit les smiles en main du résultat final
    NO_SALARY_4 = "no_salary_4" # ne peut pas poser de salaire 4
    NO_SALARY_1 = "no_salary_1" # ne peut pas poser de salaire 1
    NO_JOB_STATUS = "no_job_status" # ne recois aucune avantage a etre intérimaire ou fonctionnaire
    AVEUGLEMENT = "aveuglement" # pose avant de piocher
    SALRAPAS = "salrapas" # oblige de payer le prix exacte lors d'acquisition
    NO_MALEFICES_EFFECT = "no_malefices_effect" # peut recevoir des malefices mais ne peux pas en avoir les effets
    FREE_OBJET_MAGIQUE = "free_objet_magique" # permet d'avoir les objets magiques gratuitement
    VALUE_SPECIAL_CARDS_2 = "value_special_cards_2" # donne 2 smiles pour chaques cartes spéciales 
    DOUBLE_ANIMAL = "double_animal" # double les smiles des animaux
    STUDY_VALUE_DOUBLE = "study_value_double" # double les smiles des etudes
    CAN_FLIRT_WITH_WEDDING = "can_flirt_with_wedding" # permet de flirter pendant un marriage
    FREE_POTION = "free_potion" # permet de poser des potions gratuitement
    DOUBLE_FLIRT = "double_flirt" # double les smiles des flirts
    ADD_1_HAND_CARD = "add_1_hand_card" # ajoute une carte max dans la main
    SUB_1_HAND_CARD = "sub_1_hand_card" # retire une carte max dans la main