@startuml


class Player {
    -name : String
    -playerID : UUID
    -hand : List<Card>
    -viePersonnelle : PlayedCards
    -vieProfessionnelle : PlayedCards
    -acquisitions : PlayedCards
    -salairesDepenses : PlayedCards
    -specialCards : PlayedCards
    -permanentEffects : list<PermanentEffects>
}

enum PermanentEffects {
    NO_SICKNESS = "Pas de maladie"
}

abstract Card {
    -smiles: int
    -name: String 
}

class PlayedCard {
    - name: String
    - cards: List<Card>
}

@enduml